export const PAISES = [
    { codigo: 'AL', nombre: 'Albania' },
    { codigo: 'AD', nombre: 'Andorra' },
    { codigo: 'AM', nombre: 'Armenia' },
    { codigo: 'AT', nombre: 'Austria' },
    { codigo: 'AZ', nombre: 'Azerbaijan' },
    { codigo: 'BY', nombre: 'Belarus' },
    { codigo: 'BE', nombre: 'Belgium' },
    { codigo: 'BA', nombre: 'Bosnia and Herzegovina' },
    { codigo: 'BG', nombre: 'Bulgaria' },
    { codigo: 'HR', nombre: 'Croatia' },
    { codigo: 'CY', nombre: 'Cyprus' },
    { codigo: 'CZ', nombre: 'Czech Republic' },
    { codigo: 'DK', nombre: 'Denmark' },
    { codigo: 'EE', nombre: 'Estonia' },
    { codigo: 'FI', nombre: 'Finland' },
    { codigo: 'FR', nombre: 'France' },
    { codigo: 'GE', nombre: 'Georgia' },
    { codigo: 'DE', nombre: 'Germany' },
    { codigo: 'GR', nombre: 'Greece' },
    { codigo: 'HU', nombre: 'Hungary' },
    { codigo: 'IS', nombre: 'Iceland' },
    { codigo: 'IE', nombre: 'Ireland' },
    { codigo: 'IT', nombre: 'Italy' },
    { codigo: 'LV', nombre: 'Latvia' },
    { codigo: 'LI', nombre: 'Liechtenstein' },
    { codigo: 'LT', nombre: 'Lithuania' },
    { codigo: 'LU', nombre: 'Luxembourg' },
    { codigo: 'MK', nombre: 'Macedonia' },
    { codigo: 'MT', nombre: 'Malta' },
    { codigo: 'MD', nombre: 'Moldova' },
    { codigo: 'MC', nombre: 'Monaco' },
    { codigo: 'ME', nombre: 'Montenegro' },
    { codigo: 'NL', nombre: 'Netherlands' },
    { codigo: 'NO', nombre: 'Norway' },
    { codigo: 'PL', nombre: 'Poland' },
    { codigo: 'PT', nombre: 'Portugal' },
    { codigo: 'RO', nombre: 'Romania' },
    { codigo: 'RU', nombre: 'Russia' },
    { codigo: 'SM', nombre: 'San Marino' },
    { codigo: 'RS', nombre: 'Serbia' },
    { codigo: 'SK', nombre: 'Slovakia' },
    { codigo: 'SI', nombre: 'Slovenia' },
    { codigo: 'ES', nombre: 'Spain' },
    { codigo: 'SE', nombre: 'Sweden' },
    { codigo: 'CH', nombre: 'Switzerland' },
    { codigo: 'TR', nombre: 'Turkey' },
    { codigo: 'UA', nombre: 'Ukraine' },
    { codigo: 'GB', nombre: 'United Kingdom' },
    { codigo: 'VA', nombre: 'Vatican City' }
];
